// AUTO-GENERATED by scripts/generate-fx-sheets.py — 손으로 고치지 말 것.
// 이펙트 시트 매니페스트. main.ts 가 이 표만 보고 로드·애니메이션 등록을 한다.
// 프레임 수를 코드에 손으로 적으면 반드시 어긋난다.

export interface FxSheetSpec {
	/** 프레임 가로(px) */
	frameWidth: number;
	/** 프레임 세로(px) */
	frameHeight: number;
	/** 총 프레임 수 */
	frames: number;
	fps: number;
	/** true 면 무한 반복 — 소유자가 fxSpriteStop 으로 직접 꺼야 한다 */
	loop: boolean;
}

export const FX_SHEETS: Record<string, FxSheetSpec> = {
	// 시전 마법진 (skillCastFX 공유)
	'fx-cast-circle': { frameWidth: 256, frameHeight: 256, frames: 12, fps: 24, loop: false },
	// 원소 노바 (필살기·세트 스킬 공유)
	'fx-nova': { frameWidth: 256, frameHeight: 256, frames: 10, fps: 22, loop: false },
	// 낙뢰 기둥 (lightningFX 공유)
	'fx-bolt': { frameWidth: 128, frameHeight: 320, frames: 6, fps: 30, loop: false },
	// 검기 (방향성, +X 기준)
	'fx-slash': { frameWidth: 384, frameHeight: 192, frames: 7, fps: 24, loop: false },
	// 지속 장판 루프 (불바다·미끼 횃불·시간 감속)
	'fx-field': { frameWidth: 256, frameHeight: 256, frames: 8, fps: 11, loop: true },
	// 보호막 돔 루프 (검 방패·얼음 감옥)
	'fx-dome': { frameWidth: 192, frameHeight: 192, frames: 8, fps: 10, loop: true },
};
